//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoKmlLibrary.UnitTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locations
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public System.Data.Entity.Spatial.DbGeography Geometry { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public string Picture { get; set; }
        public string Url { get; set; }
    }
}
